name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  moduleName: pygot
  testsName: tests

trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

schedules:
  - cron: 0 0 * * *
    displayName: Daily build
    branches:
      include:
        - master
    always: true

pool:
  vmImage: $(vmImage)

strategy:
  matrix:
    linux37:
      versionSpec: '3.7'
      vmImage: ubuntu-latest
    linux38:
      versionSpec: '3.8'
      vmImage: ubuntu-latest
    windows37:
      versionSpec: '3.7'
      vmImage: windows-latest
    windows38:
      versionSpec: '3.8'
      vmImage: windows-latest


jobs:
- job: A
  steps:
  - bash: echo "A"
  
- job: B
  steps:
  - bash: echo "B"